add

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,6 +1,33 @@
-#!/bin/bash
-aclocal
-autoheader
-automake
-libtoolize -f -c
-autoconf
+#!/bin/sh
+
+# This can be changed whenever it is decided to use a new
+# autotools
+#
+# Official release tarballs should only be prepared using the
+# autotools version agreed on the swab mailing list
+#
+SUPPORTED="Centos 5.0+ "
+
+echo "Bootstrapping "
+echo "WARNING:"
+echo "WARNING: you should only do this on $SUPPORTED"
+echo "WARNING: as any other versions of autotools may produce"
+echo "WARNING: errors or silently do something unexpected"
+echo "WARNING:"
+
+echo "Create distribution timestamp"
+echo "Running aclocal" &&
+aclocal &&
+echo "Running autoheader" &&
+autoheader &&
+echo "Creating build" &&
+mkdir -p build &&
+echo "Running automake" &&
+automake --add-missing --copy --foreign 2>/dev/null
+echo "Running libtoolize" &&
+libtoolize --automake --copy && automake --add-missing --copy --foreign &&
+echo "Running autoconf" &&
+autoconf -f || exit 1
+
+echo &&
+echo "To begin installation, run \"./configure\" now"
